name: "Check a README.md file is present"

on: [push]

jobs:
  readme:
    name: "Check README.md"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check README.md"
        run: |
          ERROR=0
          # Check if main README.md exists
          if [ ! -f README.md ]; then
            echo "README.md is missing"
            ERROR=1
          fi
          # Check if README.md exists in all project directories
          for dir in $(find . -name '0x*');
          do
            if [ ! -f "$dir/README.md" ]; then
              echo "README.md is missing in $dir"
              ERROR=1
            fi
          done;
          exit $ERROR
